### ISSUE TITLE
Wrong CRUD url

### ISSUE THREAD

**Issue by allevo** [mia-platform-marketplace/Node.js-Call-CRUD-Example#16]
In the example the following line is not correct:

https://github.com/mia-platform-marketplace/Node.js-Call-CRUD-Example/blob/f9189d345759671d06d6ecfead1a8e05bc054f4f/index.js#L30

CRUD url should end with `/`:

```js
    const { statusCode, payload } = await proxy.get('/v2/riders/')
```

**Comment by FilippoRezzonico** [comment]
I fixed this and made a MR: https://github.com/mia-platform-marketplace/Node.js-Call-CRUD-Example/pull/17

**Comment by fredmaggiowski** [comment]
PR #17 merged
